config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	namespace :admin do
		resources :items do
      resources :comments
    end
    resources :users, only: [:index, :show, :destroy]
		resources :primecategories
		resources :categories
	end

  namespace :moderator do
    resources :items, only: [:index, :show, :new, :create] do
      resources :comments
    end
    resources :categories, only: [:show]
  end
	
  resources :items, only: [:index, :show] do
  	resources :comments, only: [:create]
  end
  root :to => 'items#index'
  resources :categories, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/primecategory.rb
class Primecategory < ApplicationRecord
	has_many :categories
	has_many :items
end

app/controllers/admin/primecategories_controller.rb
class Admin::PrimecategoriesController < AdminController
  before_action :set_primecategory, only: [:show, :edit, :update, :destroy]

  # GET /primecategories
  # GET /primecategories.json
  def index
    @primecategories = Primecategory.all
  end

  # GET /primecategories/1
  # GET /primecategories/1.json
  def show
  end

  # GET /primecategories/new
  def new
    @primecategory = Primecategory.new
  end

  # GET /primecategories/1/edit
  def edit
  end

  # POST /primecategories
  # POST /primecategories.json
  def create
    @primecategory = Primecategory.new(primecategory_params)

    respond_to do |format|
      if @primecategory.save
        format.html { redirect_to admin_primecategories_url, notice: 'Primecategory was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @primecategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /primecategories/1
  # PATCH/PUT /primecategories/1.json
  def update
    respond_to do |format|
      if @primecategory.update(primecategory_params)
        format.html { redirect_to admin_primecategories_url, notice: 'Primecategory was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @primecategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /primecategories/1
  # DELETE /primecategories/1.json
  def destroy
    @primecategory.destroy
    respond_to do |format|
      format.html { redirect_to admin_primecategories_url, notice: 'Primecategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_primecategory
    @primecategory = Primecategory.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def primecategory_params
    params.require(:primecategory).permit(:name, :description)
  end
end

app/controllers/primecategories_controller.rb
class PrimecategoriesController < ApplicationController
  before_action :set_primecategory, only: [:show, :edit, :update, :destroy]

  # GET /primecategories
  # GET /primecategories.json
  def index
    @primecategories = Primecategory.all
  end

  # GET /primecategories/1
  # GET /primecategories/1.json
  def show
  end

  # GET /primecategories/new
  def new
    @primecategory = Primecategory.new
  end

  # GET /primecategories/1/edit
  def edit
  end

  # POST /primecategories
  # POST /primecategories.json
  def create
    @primecategory = Primecategory.new(primecategory_params)

    respond_to do |format|
      if @primecategory.save
        format.html { redirect_to @primecategory, notice: 'Primecategory was successfully created.' }
        format.json { render :show, status: :created, location: @primecategory }
      else
        format.html { render :new }
        format.json { render json: @primecategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /primecategories/1
  # PATCH/PUT /primecategories/1.json
  def update
    respond_to do |format|
      if @primecategory.update(primecategory_params)
        format.html { redirect_to @primecategory, notice: 'Primecategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @primecategory }
      else
        format.html { render :edit }
        format.json { render json: @primecategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /primecategories/1
  # DELETE /primecategories/1.json
  def destroy
    @primecategory.destroy
    respond_to do |format|
      format.html { redirect_to primecategories_url, notice: 'Primecategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_primecategory
    @primecategory = Primecategory.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def primecategory_params
    params.require(:primecategory).permit(:name, :description)
  end
end

app/helpers/prime_categories_helper.rb
module PrimeCategoriesHelper
end

app/helpers/primecategories_helper.rb
module PrimecategoriesHelper
end

app/views/admin/primecategories/_form.html.erb
<%= form_with(model: [:admin, primecategory], local: true) do |form| %>
  <% if primecategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(primecategory.errors.count, "error") %> prohibited this primecategory from being saved:</h2>

      <ul>
      <% primecategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :primecategory_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :primecategory_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/primecategories/edit.html.erb
<h1>Editing Primecategory</h1>

<%= render 'form', primecategory: @primecategory %>

<%= link_to 'Show', admin_primecategory_path(@primecategory) %> |
<%= link_to 'Back', admin_primecategories_path %>

app/views/admin/primecategories/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Надкатегории</div>
  <table class="table">
    <thead>
      <tr>
        <th>Название</th>
        <th>Описание</th>
        <th colspan="3">Действия</th>
      </tr>
    </thead>

    <tbody>
      <% @primecategories.each do |primecategory| %>
        <tr>
          <td><%= primecategory.name %></td>
          <td><%= primecategory.description %></td>
          <td><%= link_to 'Show', [:admin, primecategory], class: "btn btn-primary" %></td>
          <td><%= link_to 'Edit', edit_admin_primecategory_path(primecategory), class: "btn btn-info" %></td>
          <td><%= link_to 'Destroy', [:admin, primecategory], method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<table>
  
</table>

<br>

<%= link_to 'Новая надкатегория', new_admin_primecategory_path %>

app/views/admin/primecategories/new.html.erb
<h1>New Primecategory</h1>

<%= render 'form', primecategory: @primecategory %>

<%= link_to 'Back', admin_primecategories_path %>

app/views/admin/primecategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @primecategory.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @primecategory.description %>
</p>

<%= link_to 'Edit', edit_admin_primecategory_path(@primecategory) %> |
<%= link_to 'Back', admin_primecategories_path %>