config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	namespace :admin do
		resources :items do
      resources :comments
    end
    resources :users, only: [:index, :show, :destroy]
		resources :primecategories
		resources :categories
	end

  namespace :moderator do
    resources :items, only: [:index, :show, :new, :create] do
      resources :comments
    end
    resources :categories, only: [:show]
  end
	
  resources :items, only: [:index, :show] do
  	resources :comments, only: [:create]
  end
  root :to => 'items#index'
  resources :categories, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :primecategory
	has_many :item_categories, :dependent => :destroy
	has_many :items, :through => :item_categories
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :primecategories
	has_many :item_categories, dependent: :destroy
	has_many :categories, through: :item_categories
	has_many :comments, dependent: :destroy
	def self.search(search)
  	where("name ILIKE ?", "%#{search}%") 
  	where("description ILIKE ?", "%#{search}%")
	end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name, :description, :primecategory_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :primecategory_id)
    end
end

app/controllers/moderator/categories_controller.rb
class Moderator::CategoriesController < ModeratorController
  before_action :set_category, only: [:show]

  
  def show
  end

  private
 
  def set_category
    @category = Category.find(params[:id])
  end

  
  def category_params
    params.require(:category).permit(:name, :description, :primecategory_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :primecategory_id, "Высшая категория" %>
    <%= form.collection_select(:primecategory_id, Primecategory.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :category_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <!-- <th>Primecategory</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <% Primecategory.all.each do |primecategory| %>
          <% if primecategory.id == category.primecategory_id %>
            <td><%= primecategory.name %></td>
          <% end %>
        <% end %>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>Новая категория</h1>

<%= render 'form', category: @category %>

<%= link_to 'Назад', categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<div class="row">
  <% Item.all.each do |item| %>
    <% if item.category_ids.include?(@category.id) %>
    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
      <div class="thumbnail">
        <img src="..." alt="...">
        <div class="caption">
          <h3><%= item.name %></h3>
          <p><%= item.description %></p>
          <p><%= link_to 'Читать далее...', item, class: "btn btn-primary", role: "button" %></p>
        </div>
        <% end %>
    </div>
  </div>
  <% end %>
</div>